# fly.toml app configuration file generated for ai-careers-cv-service on 2025-06-13T15:48:18+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-careers-cv-service'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  ENVIRONMENT = 'production'
  HOST = '0.0.0.0'
  PORT = '8000'

[processes]
  app = 'python -m uvicorn cv_service:app --host 0.0.0.0 --port 8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.health]
    port = 8000
    type = 'http'
    interval = '30s'
    timeout = '10s'
    grace_period = '30s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
